### ISSUE TITLE
Unable to render Dynamic content in html

### ISSUE THREAD

**Issue by santhoshakashs24** [django-ace/django-ace#17] opened 2020-11-23 05:34 UTC
I'm trying to use SnippetForm as:

### views.py
```python
def landing(request,*args,**kwargs):
    global content
    return render(request, 'snippet.html',{'form':SnippetForm(initial={'text': content})})

def console(request,*args,**kwargs):
     content = some text based on function 
    return render(request,'console.html',{'form': content})
```

### console.html
```html
{{form}}
```

### snippet.html
```
<div>
          <form action="" id="editor" method="post">
              {% csrf_token %}
              <div class="row">
                {{ form.as_p }}
              </div>
              <span>
                <input type="button" class="btn btn-info" name="editedContent" id="contentSubmit" value="Submit" />
                <!-- <input type="submit" class="btn btn-info" name="editedContent" id="contentSubmit"/> -->
                <input type="submit" class="btn btn-info" name="cancelContent" id="cancelOperation" value="Cancel" />
              </span>
          </form>
</div>
```

Using Ajax request to update form:
```js
$("#fileSubmit").click(function(e){
   e.preventDefault();
   var csrftoken=getCookie('csrftoken')
   var appName = $('#appNames').val()
   var fileName = $('#fileNames').val()
   console.log(appName,fileName)
   var data={'csrfmiddlewaretoken':csrftoken,group:$('#groupNames').val(),'appName':appName,'fileName':fileName,type: 'console'};
   console.log(data)
  $.ajax({
    url : "{% url 'console1:console' %}",
    type : "POST",
    data : data,
    success : function(result){
      console.log("Result",result);
      // $('#console').html(result);
      document.getElementById('id_text').innerHTML = result;
      document.getElementsByTagName('label').innerHTML = "";
      displayConsole();
    },
    error : function(error){
      console.log(error.responseText);
    }
  });
});
```

But the content is now updating can i know how to do it.. Thank you!!

**Comment by santhoshakashs24** [comment] 2020-11-23 05:35
@bradleyayers @katylava @kitsunde @kezabelle  could you please help

**Comment by kitsunde** [comment] 2020-11-23 06:23
@santhoshakashs24 It's not very polite to tag and chase people 1 minute after filing an issue, we all have jobs and things going on in our lives. I also have not touched this project since Feb 12, 2012, when it was forked from my tiny POC I don't know what you're expecting here 🤷‍♂️.

To everyone else:

I think it's super cool that it took on a life of its own. I saw the license changed at one point, and since I'm here consider this my sign-off to re-licensing any work I've done, you're all amazing.

**Comment by santhoshakashs24** [comment] 2020-11-23 07:48
@kitsunde Really sorry for that, i'm new to Issues on github. So, it said i have not assigned anyone to the issue. So, i added people to it to get the help from you guys.

**Comment by JulienPalard** [comment] 2020-11-23 07:52
> But the content is now updating

Did you meant *not* updating?

What is `id_text`?

**Comment by santhoshakashs24** [comment] 2020-11-23 07:54
Yes, it's updating the TextArea which has id="id_text" but the content is not shown on the UI

**Comment by JulienPalard** [comment] 2020-11-23 08:04
> Yes, it's updating the TextArea which has id="id_text" but the content is not shown on the UI

I see no textarea with id="id_text". Can you provide a [reprex](https://stackoverflow.com/help/minimal-reproducible-example)?

If it's not a bug from django-ace but an ask for assistance, you may better ask on stackoverflow.com, project issues are more suited for bugs and features.

**Comment by santhoshakashs24** [comment] 2020-11-23 08:07
Okay, Thank you. It's not exactly an bug from django-ace but a help which i needed. Thank you again.

**Comment by JulienPalard** [comment] 2020-11-23 08:08
Don't hesitate to drop the reprex both side, and to close this issue when your problem is fixed :)

**Closed** 2022-10-14 12:39 UTC
